---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: dev

inputs:
- name: resource-src

outputs:
- name: build-artifacts

run:
  path: resource-src/docker-dev/build-artifacts
