---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cycloid/terraform-resource

inputs:
- name: resource-src

outputs:
- name: build-artifacts

run:
  path: resource-src/docker-dev/build-artifacts
